### ISSUE TITLE
Should the module allow for importing user session variables?

### ISSUE THREAD

**Issue by proxb** [proxb/PoshRSJob#118]
Would anyone find it useful to include an option to import user session variables into the runspaces? I know it is used in Invoke-Parallel and had someone mention recently in a blog article that it was missing this as a feature. It doesn't seem like it would be hard to implement, just curious on what others think.

**Comment by MVKozlov** [comment]
I think it might be useful for beginners but can lead to great number of hidden errors and misunderstandings in "how the things work" area because it differ from mainstream `Start-Job` and `Invoke-Command` experience.

But anyway it should be implemented as `-VariablesToInclude var1, var2, othervar*` form but not in `-IncludeAllSessionVariables` as well as `-ModulesToImport` work. My Invoke-Parallel experiments ends with big frustration "why it import all my modules and variables?!" :)

**Comment by replicaJunction** [comment]
Would there be any difference between this behavior and what's currently supported with the $using: convention?

I admit I've been bitten a few times by forgetting to add the $using: prefix, but I honestly like the clarity of being very explicit in which variables get brought into the scriptblock and which don't. I could agree with @MVKozlov about a -VariablesToImport syntax, but unless there's a clear functional difference between that and $using: variables, I'm not sure I see a need for it.

Just my two cents though...take it for what it's worth. :o)

**Comment by proxb** [comment]
Thanks for the feedback @MVKozlov and @replicaJunction! 
The only reason that i am debating this was due to an article that mentioned another parallel powershell module which included this feature and was curious as to hear the opinions of others. I am definitely more in the area of sticking with $Using: as the means to bring over the variables but just wanted to make sure that I wasn't the only one with that opinion.

**Comment by proxb** [comment]
Most feedback says that this is not a needed item, so I will close this out and re-engage if more people are interested.
