### ISSUE TITLE
Functions/variables defined outside of RSJob invisible to RSJob

### ISSUE THREAD

**Issue by aex90832** [proxb/PoshRSJob#120]
Bug/Enhancement

Current Behavior: User defined functions/variables defined outside of RSJob multi-thread are not visible to to RSJob.

Expected Behavior: User can define functions/variable in the script and be able to use said function as part of the RsJob script block. This allows for a cleaner looking script. Could be a flag for Start-RsJob like -excludeexternalvariables and -excludeexternalfunctions

Using PowerShell 4.0 on Windows 7

`
Function Get-DNSName ($ip){
     try{
         $DNSName = ([System.Net.Dns]::GetHostbyAddress($ip).HostName)
         $DNSName = $DNSName.ToUpper()
         $hostName = $DNSName.Replace(".AREA52.AFNOAPPS.USAF.MIL", "")}
     catch{$hostName = $null}
     Return $hostName }

$ip = Get-Content $PSScriptRoot\hosts.txt
$date = Get-Date -Format ("yyyy-MM-dd")
$outpath = "$PSScriptRoot\FQDN-($date).CSV"

Start-RSJob -Name {"$($_)"} -Throttle 15 -ScriptBlock{
     $HostName = Get-DNSName $ip
    
    $outPut | Add-Member -MemberType NoteProperty -Name "IPAddress" -Value $IP
    $outPut | Add-Member -MemberType NoteProperty -Name "FQDN"      -Value $HostName
     
    $outPut | Export-Csv -Path $outpath  -Append -NoTypeInformation
}
`

Output presented: The term 'Get-DNSName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is corre
ct and try again.

**Comment by MVKozlov** [comment]
Now there is `-FunctionsToLoad` for functions and standart `$using `syntax for variables which solve your problem.
anyway, if you want to resolve dns in multithreaded way, you make it wrong:

if you want to speedup resolwing with multithreading there must be something like that:
`
$ip | start-rsjob -name {"$($_)"} -Throttle 15 -ScriptBlock{ Get-DNSName $_ }  -FunctionsToLoad Get-DNSName
`
and after all jobs completed you should `Get-RSJob | Receive-RSJob` and export it to csv

or if you just want to start-and-forget (note the **$using:** prefix )
```
start-rsjob -name {"$($_)"} -Throttle 15 -ScriptBlock{
 $using:ip | Foreach-Object{
[PSCustomObject]@{
  IPAddress = $_
 HostName = Get-DNSName $_ 
} | Export-Csv -Append -Path $using:outpath -NoTypeInformation
 }
 }  -FunctionsToLoad Get-DNSName
```
note the foreach-object cycle.
your **$HostName = Get-DNSName $ip** doesn;t work not only because you do not use $using syntax, but you also try to push array to your function which not support it

**Comment by aex90832** [comment]
I apologize. Rookie POSH user here. Was not aware of the $using prefix or the -FunctionsToLoad for using external functions and variables within the script block.

Excuse the terrible script block, was trying to remove simplify to show the situation I was trying to explain. I was previously using $ip | start-rsjob...


Thank you for your assistance/patience!

**Comment by proxb** [comment]
@aex90832 Did @MVKozlov 's answer satisfy your question? If so, I will go ahead and close this issue out, otherwise feel free to let us know if you have more questions with regard to this issue.

**Comment by MVKozlov** [comment]
@proxb  this is **+1** for **-ValiablesToLoad** ;-)
and may be for **-Import(_Valiable/Function/Module/Snapin_)** aliases

**Comment by aex90832** [comment]
All is good for me! Thank you!
