### ISSUE TITLE
Failed HTTP download job causes the PoshRSJob API to hang

### ISSUE THREAD

**Issue by IanM-CF** [proxb/PoshRSJob#22]
If I use a PoshRSJob version 1.1.3.0 to make a HTTP request, and that request fails for some reason, then the next call to the PoshRSJob API will hang. It is easy to reproduce the problem:

```powershell
Import-Module poshrsjob
$job = Start-RSJob -ScriptBlock {
  $ErrorActionPreference = “Stop”
  $wc = new-object net.webclient
  try
  {
    $wc.DownloadString(“http://www.google.com/not-a-valid-page-will-return-404")
  }
  finally
  {
    $wc.Dispose()
  }
}
```

The job completes almost immediately. The $job object can be queried as normal and has the expected properties (State = Failed, HasErrors = True). However, a call to get-rsjob will now hang. The same seems to be true for any of the PoshRSJob methods.

The code works perfectly when the URL is valid. The try/finally block is there for completeness - the problem occurs if it is not present.

**Comment by proxb** [comment]
Thanks for the feedback! I will investigate this and see what I can figure out.

**Comment by proxb** [comment]
Finally had some time to look at this and found that the issue lies in the terminating error that the command happens to throw in the RSJob. When ending the job, the terminating error comes through and actually forces everything to halt which means that the processing of the internal job object never actually finishes and is making everything else lock up to include the call to Get-RSJob. I've got the bug fixed up and should be uploading the patched code later tonight.

**Comment by proxb** [comment]
This issue should be fixed now. I tested with the example that you provided and it didn't have any issues.
