### ISSUE TITLE
Can't use Write-Host and Write-Verbose into a RSJob

### ISSUE THREAD

**Issue by fmichaleczek** [proxb/PoshRSJob#94]
Hello !

When I use "Write-Host" or "Write-Verbose" into a scriptblock within the command "Start-RSJob", I do not have any output. I try to use [Console]::WriteLine instead and it is working.

So, I look at the function Start-RSJob and I found in Start-RSJob at Line 410 : (there is also the same line in batch processing)

$RunspacePool = [runspacefactory]::CreateRunspacePool($InitialSessionState)

I replace with this line to add host to the runspace :
$RunspacePool = [runspacefactory]::CreateRunspacePool(1,$Throttle,$InitialSessionState,$Host)

I don't know if it is an issue or a feature :)

Could you have a look ?

**Comment by proxb** [comment]
That is very likely an issue :)  I'll take a look at this and, after some testing, get this updated.

**Comment by codykonior** [comment]
Regarding the "using write-host and write-verbose in a script block".

You can't write-host in a script block. That seems to be by design.

You can write-verbose, however, the script block itself must have $VerbosePreference set to Continue for this to work. Otherwise the write-verbose output doesn't get saved to the (Get-RsJob).Verbose stream. Furthermore if you want to see the output from Receive-RsJob you also need to specify the -Verbose flag there.

However then it mixes in a lot of verbose output from the command itself rather than just from the job. Personally I find that irritating - but one can always use the .Verbose property instead.

**Comment by proxb** [comment]
I _might_ look at removing the extra verbose output from Receive-RSJob as it was there mostly to support debugging issues with the command. That being said, the best bet to look at the Verbose data is to use the .Verbose property of the RSJob that @codykonior mentioned.

**Comment by mattp65** [comment]
I think the following slight change to WriteStream.ps1 would address the Verbose item:
`"Verbose" { $IndividualJob | Select -ExpandProperty Verbose | ForEach { Write-Verbose $_  -Verbose} }`

If the invoked script generates Verbose output, this will then output that Verbose output w/o polluting it with extra output from WriteStream itself.  This is in line with how a user would expect it to work.

**Comment by proxb** [comment]
Made some updates to the WriteStream function that may help with the Write-Verbose (and other streams). Let me know if this meets what you are looking for. I also removed a bunch of unneeded Write-Verbose from Receive-RSJob. Note that you shouldn't have to specify the streams via parameter and they should just display on Receive-RSJob.

**Comment by proxb** [comment]
@fmichaleczek Any chance that you have revisited this? Would love to know if this is meeting what you are looking for.
